In [3]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
one_hot("amazing restaurant",30)

[21, 29]

In [6]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[29, 3], [21, 29], [22, 7], [8, 23, 7], [27, 8, 20], [12, 3], [16, 8, 3], [19, 10], [19, 10], [15, 25]]


In [7]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[29  3  0  0]
 [21 29  0  0]
 [22  7  0  0]
 [ 8 23  7  0]
 [27  8 20  0]
 [12  3  0  0]
 [16  8  3  0]
 [19 10  0  0]
 [19 10  0  0]
 [15 25  0  0]]


In [17]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [18]:
X = padded_reviews
y = sentiment

In [20]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 16)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 17        
                                                                 
Total params: 137 (548.00 Byte)
Trainable params: 137 (548.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [21]:
model.fit(X, y, epochs=50, verbose=0)

In [22]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 60ms/step - loss: 0.6117 - accuracy: 1.0000


1.0

In [26]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [24]:
weights[0]

array([ 0.02438572, -0.05399483,  0.05082643,  0.01329035,  0.03342398],
      dtype=float32)

In [15]:
weights[4]

array([ 0.03008265, -0.03602169,  0.00922542,  0.02881349,  0.03456676],
      dtype=float32)

In [16]:
weights[16]

array([ 0.07437982, -0.01816378, -0.05258989,  0.09070072, -0.02193339],
      dtype=float32)